---
title: "kjg"
output: html_document
date: "2024-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#setting packages and readers
```{r}
library(tidyverse)
library(janitor)
library(here)
library(viridis)

source(here("UV_Vis_reader.R"))
source(here("FTIR_reader.R"))
```

#data locations
```{r}
UVVis_path = "~/Research/harvard/UVVis/"
FTIR_path = "~/Research/harvard/FTIR/"
```

#UV-Vis individual plotting
```{R, show_col_types = F}

UVVis_individual <- list.files(path = UVVis_path, 
                    pattern = ".csv", 
                    recursive = T, 
                    full.names = T) %>% 
  map(.f = \(x) read_uv_vis(x)) %>% 
  list_rbind()

ugh <- UVVis_individual %>% 
  count(concentration_value, concentration_type) %>% 
  mutate(conc_order = str_c(concentration_value, concentration_type))


UVVis_summ <- UVVis_individual %>% 
  summarise(mean = mean(value), 
            max = max(value), 
            min = min(value), 
            .by = c(wavelength_nm, 
                    solvent, 
                    dye, 
                    concentration,
                    concentration_value, 
                    concentration_type,
                    machine, 
                    attachment, 
                    mode)) %>% 
  mutate(mode = case_when(mode == "T" ~ "perc_transmittance", 
                          mode == "R" ~ "perc_reflectance"), 
         color = case_when(dye == "0086" ~ "black", 
                           dye == "P25" ~ "white", 
                           dye == "R910" ~ "white", 
                           .default = NA)) %>% 
  pivot_wider(names_from = c(mode), 
              values_from = c(mean, max, min)) %>% 
  mutate(mean_perc_absorbance = 100 - mean_perc_transmittance - mean_perc_reflectance, 
         max_perc_absorbance = 100 - min_perc_transmittance - min_perc_reflectance,
         min_perc_absorbance = 100 - max_perc_transmittance - max_perc_reflectance) %>% 
  pivot_longer(cols = starts_with(c("max_", "min_", "mean_")),
               names_to = c(".value", NA, "mode"), 
               names_sep = "_") %>% 
  arrange(concentration_value, wavelength_nm)

#plotting
#MinOilandSurf - 0086
UVVis_summ %>% 
  filter(solvent %in% c("MinOilandSurf"), 
         dye == "0086") %>% 
  drop_na(mean) %>% 
  ggplot(aes(x = wavelength_nm, group = interaction(concentration, solvent, dye))) + 
  geom_ribbon(aes(ymax = max, ymin = min, fill = concentration_value), alpha = 0.5) + 
  geom_line(aes(y = mean, color = concentration_value)) + 
  scale_y_continuous(limits = c(-5, 105)) +  
  scale_color_viridis_c(transform = "log2", option = "H") + 
  scale_fill_viridis_c(transform = "log2", option = "H") +
  labs(y = "Percent of Total Intensity (%)", 
       x = "Wavelength (nm)", 
       title = "0086 Perylene black in Mineral Oil with surfactant dilutions", 
       color = "concentration (mg/mL)", 
       fill = "concentration (mg/mL)") + 
  facet_wrap(facets = vars(mode))

UVVis_summ %>% 
  filter(solvent %in% c("MinOilandSurf"), 
         dye == "0086") %>% 
  drop_na(mean) %>% 
  ggplot(aes(x = wavelength_nm, group = interaction(concentration, solvent, dye))) + 
  geom_ribbon(aes(ymax = max, ymin = min, fill = as.factor(concentration_value)), alpha = 0.5) + 
  geom_line(aes(y = mean, color = as.factor(concentration_value))) + 
  scale_y_continuous(limits = c(-5, 105)) + 
  labs(y = "Percent of Total Intensity (%)", 
       x = "Wavelength (nm)", 
       title = "0086 Perylene black in Mineral Oil with surfactant dilutions", 
       color = "concentration (mg/mL)", 
       fill = "concentration (mg/mL)") + 
  facet_wrap(facets = vars(mode))


#IPA - P25
UVVis_summ %>% 
  filter(solvent %in% c("IPA"), 
         dye == "P25") %>% 
  drop_na(mean) %>% 
  ggplot(aes(x = wavelength_nm, group = interaction(concentration, solvent, dye))) + 
  geom_ribbon(aes(ymax = max, ymin = min, fill = concentration_value), alpha = 0.5) + 
  geom_line(aes(y = mean, color = concentration_value)) + 
  scale_y_continuous(limits = c(-5, 105)) +  
  scale_color_viridis_c(transform = "log2", option = "H") + 
  scale_fill_viridis_c(transform = "log2", option = "H") +
  labs(y = "Percent of Total Intensity (%)", 
       x = "Wavelength (nm)",
       title = "P25 in IPA dilutions", 
       color = "concentration (mg/mL)", 
       fill = "concentration (mg/mL)") + 
  facet_wrap(facets = vars(mode))

UVVis_summ %>% 
  filter(solvent %in% c("IPA"), 
         dye == "P25") %>% 
  drop_na(mean) %>% 
  ggplot(aes(x = wavelength_nm, group = interaction(concentration, solvent, dye))) + 
  geom_ribbon(aes(ymax = max, ymin = min, fill = as.factor(concentration_value)), alpha = 0.5) + 
  geom_line(aes(y = mean, color = as.factor(concentration_value))) +
  scale_y_continuous(limits = c(-5, 105)) + 
  labs(y = "Percent of Total Intensity (%)", 
       x = "Wavelength (nm)", 
       title = "P25 in IPA dilutions", 
       color = "concentration (mg/mL)", 
       fill = "concentration (mg/mL)") + 
  facet_wrap(facets = vars(mode))


#IPA - R960
UVVis_summ %>% 
  filter(solvent %in% c("IPA"), 
         dye == "R960") %>% 
  drop_na(mean) %>% 
  ggplot(aes(x = wavelength_nm, group = interaction(concentration, solvent, dye))) + 
  geom_ribbon(aes(ymax = max, ymin = min, fill = concentration_value), alpha = 0.5) + 
  geom_line(aes(y = mean, color = concentration_value)) + 
  scale_y_continuous(limits = c(-5, 105)) + 
  scale_color_viridis_c(transform = "log2", option = "H") + 
  scale_fill_viridis_c(transform = "log2", option = "H") +
  labs(y = "Percent of Total Intensity (%)", 
       x = "Wavelength (nm)", 
       title = "R960 in IPA dilutions", 
       color = "concentration (mg/mL)", 
       fill = "concentration (mg/mL)") + 
  facet_wrap(facets = vars(mode))

UVVis_summ %>% 
  filter(dye == "R960") %>% 
  drop_na(mean) %>% 
  ggplot(aes(x = wavelength_nm, group = interaction(concentration, solvent, dye))) + 
  geom_ribbon(aes(ymax = max, ymin = min, fill = as.factor(concentration_value)), alpha = 0.5) + 
  geom_line(aes(y = mean, color = as.factor(concentration_value), linetype = solvent)) + 
  scale_y_continuous(limits = c(-5, 105)) + 
  labs(y = "Percent of Total Intensity (%)", 
       x = "Wavelength (nm)", 
       title = "R960 in IPA dilutions", 
       color = "concentration (mg/mL)", 
       fill = "concentration (mg/mL)") + 
  facet_wrap(facets = vars(mode))

UVVis_summ %>% 
  filter(concentration_value == 0, mode == "transmittance") %>% 
  ggplot(aes(x = wavelength_nm, y = mean, color = solvent)) + 
  geom_line()
```

#FTIR individual plotting
```{r}
FTIR_individual <- list.files(path = FTIR_path, 
                              pattern = ".CSV", 
                              recursive = T, 
                              full.names = T) %>% 
  map(.f = \(x) read_FTIR(x)) %>% 
  list_rbind() %>% 
  filter(value <= 100)

FTIR_summ <- FTIR_individual %>% 
  summarise(mean = mean(value), 
            max = max(value), 
            min = min(value), 
            .by = c(wavelength_nm, 
                    solvent, 
                    dye, 
                    concentration, 
                    machine, 
                    attachment, 
                    mode)) %>% 
  mutate(mode = case_when(mode == "T" ~ "perc_transmittance", 
                          mode == "R" ~ "perc_reflectance"), 
         color = case_when(dye == "0086" ~ "black", 
                           dye == "P25" ~ "white", 
                           dye == "R910" ~ "white", 
                           .default = NA)) %>% 
  pivot_wider(names_from = c(mode), 
              values_from = c(mean, max, min)) %>% 
  mutate(mean_perc_absorbance = 100 - mean_perc_transmittance - mean_perc_reflectance, 
         max_perc_absorbance = 100 - min_perc_transmittance - min_perc_reflectance,
         min_perc_absorbance = 100 - max_perc_transmittance - max_perc_reflectance) %>% 
  pivot_longer(cols = starts_with(c("max_", "min_", "mean_")),
               names_to = c(".value", NA, "mode"), 
               names_sep = "_")


FTIR_summ %>%
  filter(mode == "absorbance") %>% 
  ggplot(aes(x = wavelength_nm, y = mean, color = concentration, linetype = solvent)) + 
  geom_line()
```


#combined plotting
```{r}
total_summ = bind_rows(FTIR_summ, UVVis_summ) %>% 
  mutate(light_range = factor(case_when(wavelength_nm >= 10 & 
                                   wavelength_nm < 400 ~ "UV", 
                                 wavelength_nm >= 400 & 
                                   wavelength_nm < 750 ~ "Visible",
                                 wavelength_nm >= 750 & 
                                   wavelength_nm < 2500 ~ "NIR", 
                                 wavelength_nm >= 2500 & 
                                   wavelength_nm < 10000 ~ "MIR", 
                                 wavelength_nm >= 10000 & 
                                   wavelength_nm < 1000000 ~ "FIR"), 
                              levels = c("UV", 
                                         "Visible", 
                                         "NIR", 
                                         "MIR", 
                                         "FIR")
                              ),
         mode = factor(case_when(mode == "absorbance" ~ "Abs.", 
                                 mode == "transmittance" ~ "Tran.", 
                                 mode == "reflectance" ~ "Ref."), 
                       levels = c("Ref.", "Tran.", "Abs.")), 
         mean = mean / 100, 
         min = min / 100, 
         max = max / 100
         )

total_summ %>% 
  filter(color == "black",
         light_range %in% c("Visible", "NIR", "MIR")) %>% 
  drop_na(mean) %>% 
  ggplot(aes(x = wavelength_nm, 
             y = mean, 
             color = concentration, 
             linetype = solvent)) + 
  geom_line() + 
  facet_grid(cols = vars(light_range), 
             rows = vars(mode), 
             scales = "free_x", 
             switch = "both") + 
  theme(axis.text.x = element_text(size = 0), 
        axis.ticks = element_line(size = 0), 
        axis.title = element_text(size = 0)) 
  
```