---
title: "kjg"
output: html_document
date: "2024-06-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)

source("~/Research/harvard/Code/UV_Vis_reader.R")
```

```{R}

UVVis_individual <- list.files(path = "~/Research/harvard/UVVis/", 
                    pattern = ".csv", 
                    recursive = T, 
                    full.names = T) %>% 
  map(.f = \(x) read_uv_vis(x)) %>% 
  list_rbind()

UVVis_summ <- UVVis_individual %>% 
  summarise(mean = mean(value), 
            max = max(value), 
            min = min(value), 
            .by = c(wavelength_nm, 
                    solvent, 
                    dye, 
                    concentration, 
                    machine, 
                    attachment, 
                    mode)) %>% 
  mutate(mode = case_when(mode == "T" ~ "perc_transmission", 
                          mode == "R" ~ "perc_reflection")) %>% 
  pivot_wider(names_from = c(mode), 
              values_from = c(mean, max, min)) %>% 
  mutate(mean_perc_absorbance = 100 - mean_perc_transmission - mean_perc_reflection, 
         max_perc_absorbance = 100 - min_perc_transmission - min_perc_reflection,
         min_perc_absorbance = 100 - max_perc_transmission - max_perc_reflection) %>% 
  pivot_longer(cols = starts_with(c("max_", "min_", "mean_")),
               names_to = c(".value", NA, "mode"), 
               names_sep = "_")


UVVis_summ %>% 
  filter(mode == "absorbance") %>% 
  ggplot(aes(x = wavelength_nm, group = interaction(concentration, solvent))) + 
  geom_ribbon(aes(ymax = max, ymin = min, fill = solvent), alpha = 0.5) +
  geom_line(aes(y = mean, color = solvent, linetype = concentration)) +
  scale_y_continuous(limits = c(-5, 105)) + 
  labs(y = "Absorbance (%)", x = "Wavelength (nm)")
```